version: '3.5'

networks:
  mysql:
    driver: bridge

services:
  mysql:
    image: mysql:5.7.19
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: mysql_reddit
    restart: always
    volumes:
      - ${pwd}/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: reddit
      MYSQL_USER: reddit
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass_root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - mysql